name: Linting

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        uses: wearerequired/lint-action@master
        with:
          continue_on_error: false
          auto_fix: false
          eslint: true
          stylelint: true
